### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by rautamiekka**
Lots of changes. Ignore the other commits, the bottom-most one is the one.

### CODE REVIEW

**Review by Kreyren — APPROVED** [review]

**Comment by Kreyren** [comment]
Checking changes now

**Review by Kreyren — APPROVED** [review]
I don't see anything that would disagree with ethical codex, approved.

Thanks for contrib, very helpful!

**Comment by rautamiekka** [comment]
You're welcome. I saw so many so bad mistakes I couldn't resist.

**Comment by rautamiekka** [comment]
My bad on the closing, I thought this was merged but not closed.

**Comment by Kreyren** [comment]
> My bad on the closing, I thought this was merged but not closed.

np, i will review the changes (in case i miss something) when i have the time since i'm focusing on the ebuild development atm. 

Any suggestions are always welcomed ^^

**Comment by Kreyren** [comment]
Closing since the MR is adapted in KUWDS.sh already.

**Pull request closed without merging**
